migrations:
  run: false
redis:
  image: redis:7-alpine
  replicas: 1
postgres:
  image: postgres:16-alpine
  storage: 1Gi
  credentials:
    database: collabboard
    user: collabboard
    password: collabboard123
    appPassword: collabboard_app_pw123
api:
  image:
    repository: ghcr.io/ruckerhans/collabboard-api
    tag: 7a09ed6978bbb697c02956c11735aa90ef8cd8bd
  replicas: 3
  jwtSecret: local-dev-collabboard-secret
  config:
    corsOrigin: http://localhost
    jwtExpiry: 7d
    googleCallbackUrl: http://localhost/api/auth/google/callback
front:
  image:
    repository: ghcr.io/ruckerhans/collabboard-front
    tag: 7a09ed6978bbb697c02956c11735aa90ef8cd8bd
  replicas: 1