apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: collabboard
  labels:
    app: ingress
    {{- include "collabboard.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3050
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3050
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front
                port:
                  number: 3000